services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html   # Solo para edición si quieres
      - vendor:/var/www/html/vendor
    environment:
      APP_ENV: production
      APP_DEBUG: false
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      QUEUE_CONNECTION: database
      MAIL_MAILER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_FROM_ADDRESS: admin@example.com
      MAIL_FROM_NAME: "Library System"

volumes:
  vendor:
