services:
  # Servidor Nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
      - app_storage:/var/www/html/storage
    depends_on:
      - app
    networks:
      - laravel-network

  # Servidor PHP-FPM (app)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - app_storage:/var/www/html/storage
    environment:
      - PHP_UPLOAD_MAX_FILESIZE=128M
    expose:
      - "9000"
    env_file: .env
    networks:
      - laravel-network

  # Queue worker
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan queue:work
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - app_storage:/var/www/html/storage
    depends_on:
      - app
    networks:
      - laravel-network

  # Scheduler
  schedule:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan schedule:work
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - app_storage:/var/www/html/storage
    depends_on:
      - app
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  app_storage:
