services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html           # Monta tu proyecto para edición en tiempo real
      - vendor:/var/www/html/vendor  # Mantener dependencias PHP
      - node_modules:/var/www/html/node_modules  # Mantener dependencias Node
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      QUEUE_CONNECTION: database
      MAIL_MAILER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_FROM_ADDRESS: admin@example.com
      MAIL_FROM_NAME: "Library System"

volumes:
  vendor:
  node_modules:
