
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-vue-app
    container_name: laravel-app
    restart: unless-stopped
    environment:
      - PHP_UPLOAD_MAX_FILESIZE=128M
    volumes:
      - ./database/database.sqlite:/var/www/html/database/database.sqlite
      - app_storage:/var/www/html/storage
    networks:
      - laravel-network
    expose:
      - "9000"  # Puerto interno para PHP-FPM, usado por Nginx

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"  # Aquí sí exponemos HTTP al host
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./database/database.sqlite:/var/www/html/database/database.sqlite
      - app_storage:/var/www/html/storage
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - laravel-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-vue-app
    container_name: laravel-queue
    command: ["php", "artisan", "queue:work", "--verbose", "--tries=3", "--timeout=90"]
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./database/database.sqlite:/var/www/html/database/database.sqlite
      - app_storage:/var/www/html/storage
    networks:
      - laravel-network

  schedule:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-vue-app
    container_name: laravel-schedule
    command: ["php", "artisan", "schedule:work"]
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./database/database.sqlite:/var/www/html/database/database.sqlite
      - app_storage:/var/www/html/storage
    networks:
      - laravel-network

volumes:
  app_storage:

networks:
  laravel-network:
    driver: bridge
