
services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-vue-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:your_app_key_here
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000

      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite

      - MAIL_MAILER=log
      - QUEUE_CONNECTION=database
      - SESSION_DRIVER=database
      - SESSION_LIFETIME=120

      - VITE_APP_NAME="${APP_NAME}"
      - VITE_APP_URL="${APP_URL}"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
