
services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      QUEUE_CONNECTION: database
      MAIL_MAILER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_FROM_ADDRESS: admin@example.com
      MAIL_FROM_NAME: "Library System"
