services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    depends_on:
      - db

  db:
    image: sqlite:latest
    container_name: laravel_db
    volumes:
      - ./database:/database

volumes:
  vendor:
  node_modules:
